### PR TITLE
Create 03-extras

### PR DESCRIPTION
**Pull request by Nottt**
1. Download latest ffmpeg executable if -e ffmpeg=true
2. Install mkvtoolnix if -e mkvtoolnix=true

I've tested it, it works and it doesn't affect anything if you don't use the variables

### CODE REVIEW

**Comment by Nottt** [comment]
ok then...don't complain if people never contribute then :woman_facepalming:

**Comment by hotio** [comment]
I won't, certainly will not if it's this messy. What even made you think I would merge after telling you No already?

**Comment by Nottt** [comment]
Why is this messy? It does literally nothing unless enabled by the user haha.. I thought you were a reasonable person, but whatever

**Comment by hotio** [comment]
Just because you can't have it your way makes me unreasonable... Just fork it and maintain your own container.

**Comment by hotio** [comment]
To elaborate on why this is messy....

1) no use of `# shellcheck shell=bash`, so I doubt if it validates
2) use of `[ ]` instead of `[[ ]]`
3) use of `$FFMPEG` instead of `${FFMPEG}`
4) no identation
5) irregular use of comments
6) unnecessary installation of wget
7) not in line with the rest of scripts, aka usage of `$(mktemp)`
8) no cleanup of apt after update & install
9) no error handling (warning) if download fails
10) if both ffmpeg and mkvtoolnix are enabled, you are trying to install wget twice

Bonus:
11) It's a bad user experience, waiting until all of this is installed on every boot
12) I already told you NO, because something else was on the todo list that might solve this...

**Comment by Nottt** [comment]
lmao you still are at it? first of all, I could have fixed anything had you just said what you wanted but lets go with your points:

Funny because if you paste my code at https://www.shellcheck.net/ it finds no issues, and regardless I didn't add that because I didn't felt it was really needed or made a diference

2) that's [subjective](https://stackoverflow.com/questions/3427872/whats-the-difference-between-and-in-bash/3427931) as would have made no difference here and using [] is not inherently wrong

3) I'd like to know what difference you think it'd make here 

4-5) that's subjective and affects nothing, get treatment for your OCD

6-8) Nobody cares about a few KB's of disk space, but I could have fixed that if you knew how to talk ;)

9) If it fails, which it'd be very hard radarr will survive fine, and any scripts it breaks will report it in the logs already

10) this is by design since it ensures wget will be installed if you want to install just one or another. It wont fail the command and nothing will happen by being there twice, but feel free to write 2x the code to avoid it doing that way

Bonus:

11) It's fun hearing this from someone whose dockers does everything after boot
12) So why are you reviving this? :laughing:

**Comment by hotio** [comment]
lol, we've been talking about you on the cloudbox discord, you really are a turd of a person it seems.

But, let me tell you a little secret, my repo, so my silly subjective rules apply, if you wanna mold your turd your way, go right ahead.

There's something messed up with you kid.

**Comment by hotio** [comment]
Output of your code BTW:

```
Line 1:
#!/usr/bin/with-contenv bash
^-- SC1008: This shebang was unrecognized. ShellCheck only supports sh/bash/dash/ksh. Add a 'shell' directive to specify.
```

**Comment by Nottt** [comment]
let it go then bro :) I'm not even thinking about you anymore... and yes, you just need add `# shellcheck shell=bash` to fix that and see there are no issues with the code that actually matters itself haha

**Comment by hotio** [comment]
haha, lol, bro, give me a break

**Comment by hotio** [comment]
You've been bothering me since september 2017.

NOW IT'S MY TURN

**Comment by mrhotio** [comment]
Offensive messages have been removed, please seek help. It will not get merged.

**Comment by mrhotio** [comment]
Thanks for the PM you sent me 6 months later, yet again being offensive....just pathetic. lol

**Pull request closed without merging**
